Component({
  mixins: [],
  data: {},
  props: {
    onekitClass:"",
    onekitStyle:"",
    id:"",
    url:"",
    delta:0,
    openType:"navigate",
    hoverClass:"navigator-hover",
    hoverStartTime:"",
    hoverStayTime:"",
    hoverStopPropagation:false,
  },
  didMount() {},
  didUpdate() {},
  didUnmount() {},
  methods: {},
});
